//------------------------------------
// ENVIRONMENT book
//
// Template for requirement:
//[[ex-keyword]] 
//`{counter:environment}`
// Requirement

// {missing} [Corresponding Artifact]
//------------------------------------
== Environment

=== Explanatory text
In the second iteration we refine the information and build the environment model, using the programming language. During modelling we identify implicit assumptions which should be carefully listed and further verified with the stakeholders.


=== E.1 Glossary

The new terms enrich the glossary as soon as they appear in requirements specification process.

[[ECU]]
{Electronic control unit (ECU)}:: An embedded unit in the vehicle that controls one or more electrical systems, such as the engine control unit or the human-machine interface.  

[[Race_control_unit]]
{Race control unit}:: Roborace representatives who are responsible for monitoring and supervising the practice sessions, the qualifying sessions and the race itself.

[[Curb]]
{Curb}:: Flat curbstones lining the corners or chicanes of racing tracks. They are often painted red and white, and are intended to prevent unauthorized short-cuts and keep the racers safely on the track.

[[Obstacle]]
{Obstacle}:: Any physical or virtual object on a racetrack apart from the ego vehicle

[[Inside_Outside_lines]]
{Inside line, outside line}:: White lines on the sides of a race track, defining a drivable area

[[Drivable_area]]
{Drivable area}:: Safe for driving area of a race track, bounded by Inside line and Outside line.

[[The_pits]]
{Pit}:: An area of a racetrack where teams' garages are situated and pit stops are conducted.

[[Pit_lane]]
{Pit lane}:: A lane, adjacent to a racetrack, which connects the racetrack with the pits.

[[Pit_stop]]
{Pit stop}:: A pause for recharging, new tyres, repairs, mechanical adjustments, as a penalty, or any combination of the above

[[Racetrack]]
{Racetrack}:: A circular road with a hard surface built for racing of the vehicles

[[DNF]]
{DNF}:: Did Not Finish. A run is scored as a DNF when a portion of the course was not completed or when a car fails on course.

[[Ego_vehicle]]
{Ego vehicle}:: The vehicle, the behaviour of which is of primary interest.

[[System]]
{System}:: .

[[INS]]
{Inertial navigation system}:: module consisting of a dual-antenna GNSS and an IMU , which are pre-fused to obtain a high frequency pose, velocity, and accelerations.

[[IMU]]
{Inertial measurement unit (IMU)}:: an electronic device that measures vehicle's specific force, angular rate, and orientation

[[GNSS]]
{Global Navigation Satellite System (GNSS)}:: High precision satellite-based positioning receiver.

[[Lidar]]
{Lidar}:: a sensor that uses infrared laser light to image surrounding objects

[[Radar]]
{Radar}:: a sensor that detrrmines the presence and location of surrounding objects by measuring the time for the echo of a radio wave to return from them and the direction from which it returns.

[[OSS]]
{Optical Speed Sensor (OSS)}:: a sensor that provides direct longitudinal and lateral speed measurements, which are not affected by wheel drift.

=== E.2 Components

Racetrack:: 

We model the racetrack as the sequence of coordinate tuples [(x1, y1), (x2, y2)] , which represent the coordinates of the points on the inside and outside line along the track. The first element of the sequence corresponds to the starting line. Note, that representing coordinates on a 2D plane we implicitely assume that the track is completely flat (which generally might not be true). We reflect this in the assumptions section.

.The `RACETRACK` class
[source, eiffel]
----
deferred class
	RACETRACK

feature

	map: MAP
			-- Coordinates of the bounding lines

	starting_line: TUPLE [LOCATION, LOCATION]
			-- Coordinates of the crossings of starting line with track bounding lines

	starting_grid: ARRAY [LOCATION]
			-- Coordinates of the middles of the front lines of the starting grid positions
			-- n-th element corresponds to n-th starting position.

end
----

.The `RACETRACK_MAP` class
[source, eiffel]
----
deferred class
	RACETRACK_MAP

feature

	track_borders: SEQUENCE [TUPLE [LOCATION, LOCATION]]
			-- Coordinates of the bounding lines of racetrack

end
----

[TIP]
====
You can directly include the source code itself:
[source, eiffel]
----
include::Roborace_spec/Environment/map.e[]
----

====
The starting grid is modeled as an array of coordinates of the middles of the front lines of the starting grid positions. The n-th element of the array corresponds to the n'th place on the starting grid.

As the initial phases of the development focus on the key features of the software, some environment details are ignored (which should be reflected in the assumptions section). We assume that the track surface is flat, clean, in good conditions, with no potholes and not slippery. The impact of the racetrack surface conditions can be introduced later in the development. 

During the race the only traffic signs that appear are the flags shown by the Roborace team. We assume that this information is received via V2X interface rather than preceived visually.

As the localization information is provided by the Roborace, we do not consider landmarks. 

At the current stage of the Roborace championship driving on curbs is not allowed. As the curbs are located outside of a racetrack (behind the inside or outside line), we ignore their existence.

Vehicles :: Competing race cars can be modeled as the instances of a RACECAR

Obstacles :: The obstacles can be of a different nature: real and virtual, dynamic and static. Virtual obstacles are introduced by the Roborace team during the race. If the car hits the virtual obstacles it is ot damaged; yet the bonus or penalty time will be added to a total race time. Real obstacles currently are not present, yet there might be an unexpected obstacle on a racetrack (such as a stray dog or some object bought by the wind. We capture the commonality of the different obstacle types through inheritance mechanism.

Surroundings, spectators :: We ignore the surrondingd and spectators 

Weather conditions :: We ignore the weather conditions at the moment. 

Race control unit :: 

Telemetry system is the system that monitors current parameters of the race car. The developed software shall support the corresponding interface.

Race engineers take care of the hardware, which we ignore. Race engineers also check the software before the race which should be taken into account in the project development planning.

Race rules evolve through the championship so the model should support the change.

.The `BASIC_RULES` class
[source, eiffel]
----
deferred class
	BASIC_RULES

feature
	num_laps: INTEGER
		--Number of laps in one attempt

	num_attempts: INTEGER
		--Number of attemps

	time_limit: INTEGER
		--Time limit for the racing session (minutes)

end
----

.The `RULES` class
[source, eiffel]
----
deferred class
	RULES

inherit
	BASIC_RULES
	
feature
	bonus_time_static: INTEGER
		--Time reward for collecting a bonus (seconds)

	penalty_time_static: INTEGER
		--Penalty time for hitting a static obstacle

	penalty_time_moving: INTEGER
		--Penalty time for hittig a moving obstacle

	static_obstacle_size: TUPLE[REAL, REAL]
		--Static obstacle size (bounding box)

	static_bonus_obstacle_size: TUPLE[REAL, REAL]
		--Static bonus obstacles size (bounding box)

	dynamic_obstacle_size: TUPLE[REAL, REAL]
		--Dynamic obstacles size (bounding box)

end
----



Vehicle operator :: The vehicle operator runs the software to start the race. He can also request a safe or emergency stop during the race. The corresponding interface should be developed.

Sensors :: We capture the commonalities between different types of sensors through the inheritance mechanism. 

.The `SENSOR` class
[source, eiffel]
----
deferred class
	SENSOR

feature
	position: LOCATION
		--location in the racecar coordinate system

	update_rate: REAL
		--sensor update rate
end
----

The abstract sensor class reflects the features common to all sensor. The class describing a particular sensor class inherits from a SENSOR class and further soecifies features applicable to that particular sensor type (see the example of the LIDAR class)

.The abstract `LIDAR` class
[source, eiffel]
----
deferred class
	LIDAR

inherit
	SENSOR
	
feature
	point_cloud: ARRAY2 [LOCATION]
		-- m by n matrix of detected points in lidar coordinate system

	distance: ARRAY2 [REAL]
		-- m by n matrix of distances to object points

	orientation: ORIENTATION
		-- Lidar orientation in the racecar coordinate system	

end
----

To combine all environment properties into one model, we create the ENVIRONMENT class which references all environment components:

.The abstract `ENVIRONMENT` class
[source, eiffel]
----
deferred class
	ENVIRONMENT

feature
	obstacles: BAG[OBSTACLE]
		--Set of detected obstacles on racetrack

	roborace: ROBORACE
		--Race control unit

	race: RACE
		--Current race details

	sensors: SENSORS
		--Set of sensos insalled of the vehicle

end
----

Here the Sensors class represents a particular sensors set. As the sensors location on a race car can be changed by the teams, this can be reflected upon creating an instance of SENSORS class and assigning particular location to each sensor.

.The `SENSORS` class
[source, eiffel]
----
deferred class
	SENSORS

feature
  -- The set of sensors corresponds to racecar specification
	lidar1: LIDAR
	lidar2: LIDAR
	lidar3: LIDAR
	lidar4: LIDAR
	radar1: RADAR
	radar2: RADAR
	ins: INS
	camera1: CAMERA
	camera2: CAMERA
	oss: OSS

end
----

=== E.3 Constraints

There should be at least one requirement that covers each constraint. For the given constraints the following requirements are derived:

C1. A car starts a race positioned at the starting grid of the racetrack. (business rule)

C2. A car shall not accelerate and brake at the same moment [source: interview with Ilya 09/0C2. 3/21] (engineering decision)

C3. A car shall not drive on the curbs [source: interview with Ilya 09/03/21] (business rule)

C4. A car may receive a speed limit during the race and shall react accordingly [source: interview with Ilya 09/03/21] (business rule)

C1 goes to a precondition of a race scenario: When the car starts the race, it should be located at de designated position of a starting grid. Note, that in order to express this in a programming language, the notion "located" should be difined more precisely. Here we mean that the centre of a front side of the car's bounding box should be located withing a specified margin from the relevant starting grid position.

C2 goes to the preconditions of the accelerate and brake operations:
[source, eiffel]
----
feature
	is_braking: BOOLEAN
		deferred
		end
		
	is_accelerating: BOOLEAN
		deferred
		end
		
	accelerate (a: REAL)
		require
			is_braking = False
			a /= 0
		deferred
		ensure is_accelerating = True
		end

	brake (b: REAL)
		require
			is_accelerating = False
			b > 0
		deferred
		ensure is_braking = True
		end
----

C3 is expressed in a class invariant which says that at all times the car's 4 wheels must stay within the track limits.

C4 turns into the requirements: 

The system shall support the V2X interface

When the system receives via V2X a speed limit, it shall adjust the current speed and not exceed the new speed limit till the end of the race or the new speed limit is received.

=== E.4 Assumptions
The localization data is provided during the race in real time [source: interview with Ilya 09/03/21]

The coordinates of obstacles and bonuses are sent by V2X during the race 150m ahead  [source: interview with Ilya 09/03/21]

The track 2d-map is provided before the race [source: interview with Ilya 09/03/21]

All roborace participants are able to communicate in English

The measured vehicle’s speed equals to actual vehicle’s speed [source: interview with Ilya 09/03/21]

The estimated vehicle’s pose equals to actual vehicle’s pose with an accuracy 5-10cm [source: interview with Ilya 09/03/21]

The influence of weather conditions on car dynamics is not taken into consideration.

The influence of tyre wear-off on car dynamics is not taken into consideration.

The influence of track surface degradation during the race is not taken into consideration.

The racetrack surface is clean and in good conditions.

The racetrack surface is not slippery.

If there is no wheel slipping, a car is moving towards its heading direction.

=== E.5 Effects

* As the Roborace is initially created as a self-driving cars competition, the software implementation should not have any effects on the environment
* Currently the software is checked by the Roborace team before each competition. When the system is fully implemented, this process might change.
* The implementation of fully autonomous racing vehicles will lead to a redesign of the racing championship, as the racers' personalities play an important role in it. These changes are out of scope of the RMPS project.


=== E.6 Invariants

The invariants turn into the class invariants 

In a normal mode all four wheels stay within the racetrack limits

In a normal mode the vehicles move in the racing direction


