
== System

=== S.1 List of components
The software includes the following modules:

. Perception module
. Mapping and localization
. Planning	
. Control

=== S.2 Provided functionality

The system shall generate 2D and 3D map of a racetrack [Mapping and localization]

The system shall provide the position and orientation of the AV [Mapping and localization]

The system shall calculate the racing line (path and velocity) for a given track [Planning]

The system shall find the fastest overtaking maneuver for the car (local path and velocity) [Planning]

The system shall generate the control commands [Control]

The system shall detect and localize obstacles and another vehicles [Perception]

The system shall provide object tracking and path prediction [Perception]

The system shall perform road segmentation: detect drivable space, road defects [Mapping and localization]



=== S.3 Provided interfaces

* Data input from the sensors

* Race control unit
** obstacles location
** start command
** stop command
** allow to turn on AI driver
** red and green flags
** safe stop request
** emergency stop request
** speed limit

* Safety module

=== S.4 Example scenarios


* Avoid_obstacle_or_stop [stop in front of the obstacle, or if not feasible - pass by]
* Move_to_the_pitlane [upon request]
* Race_no_obstacles [demonstrate fastest lap]
* Race_in_metaverse [collect bonus obstacles and avoid penalty obstacles]
* Race_with_dynamic_obstacles
* Race_with_overtaking
* Emergency_stop [upon request]
* Safe_stop [upon request]


=== S.5 Prioritization
At this stage no prioritization is defined.


Priority scenario:
* Race_no_obstacles [demonstrate fastest lap]

* Race_in_metaverse [collect bonus obstacles and avoid penalty obstacles]

* Emergency_stop [upon request]

* Safe_stop [upon request]

=== S.6 Verification and acceptance criteria
At this stage is not defined.

  
